### ISSUE TITLE
Letters are not aligned

### ISSUE THREAD

**Issue by WhyNotHugo** [MaxVerevkin/wlr-which-key#2]
The letters on the first row are not properly aligned; each one is slightly further right than the last.

![image](https://user-images.githubusercontent.com/730811/232482255-5516facb-04d3-49cf-a025-643f4cd09c2d.png)

**Comment by MaxVerevkin** [comment]
Was left alignment expected? Or center alignment?

**Comment by WhyNotHugo** [comment]
I expected left aligned.

I only just realise that they're right aligned. Because in this particular example they're sorted from widest to narrowest it just looks like they're each slightly further right than the previous. They're not misaligned though.

**Comment by MaxVerevkin** [comment]
IDK if it makes sense to make this configurable. In any case, I don't mind what the alignment is because I use a monospaced font.

**Comment by WhyNotHugo** [comment]
Indeed, I've configured a monospace font and this is now a non-issue for me too.

Shall I go ahead and close this?
