### ISSUE TITLE
Corner radius = 0 messes up margins

### ISSUE THREAD

**Issue by WhyNotHugo** [MaxVerevkin/wlr-which-key#4]
See screenshot with `corner_r: 0`:

![image](https://user-images.githubusercontent.com/730811/232505697-8f7214a2-1a9d-4752-ad75-7542d94226a3.png)

**Comment by WhyNotHugo** [comment]
Right, the usual spacing is equal to the corner radius, which is (with the default settings) a larger number than the border width.

Perhaps this spacing should change from `corner_r` to `max(corner_r, border_width)`?

**Comment by WhyNotHugo** [comment]
No, such a naive approach did not work:

```diff
@@ -106,12 +108,17 @@ impl Menu {
     pub fn render(&self, config: &config::Config, cairo_ctx: &cairo::Context) -> Result<()> {
         let fg_color = config.color;
 
+        let spacing = [config.corner_r, config.border_width]
+            .into_iter()
+            .max_by(f64::total_cmp)
+            .expect("a max exists");
+
         for (i, comp) in self.items.iter().enumerate() {
             comp.key_comp.render(
                 cairo_ctx,
                 text::RenderOptions {
-                    x: config.corner_r + self.key_col_width - comp.key_comp.width,
-                    y: config.corner_r + self.item_height * (i as f64),
+                    x: spacing + self.key_col_width - comp.key_comp.width,
+                    y: spacing + self.item_height * (i as f64),
                     fg_color,
                     height: self.item_height,
                 },
@@ -119,8 +126,8 @@ impl Menu {
             self.arrow.render(
                 cairo_ctx,
                 text::RenderOptions {
-                    x: config.corner_r + self.key_col_width,
-                    y: config.corner_r + self.item_height * (i as f64),
+                    x: spacing + self.key_col_width,
+                    y: spacing + self.item_height * (i as f64),
                     fg_color,
                     height: self.item_height,
                 },
@@ -128,8 +135,8 @@ impl Menu {
             comp.val_comp.render(
                 cairo_ctx,
                 text::RenderOptions {
-                    x: config.corner_r + self.key_col_width + self.arrow.width,
-                    y: config.corner_r + self.item_height * (i as f64),
+                    x: spacing + self.key_col_width + self.arrow.width,
+                    y: spacing + self.item_height * (i as f64),
                     fg_color,
                     height: self.item_height,
                 },
```

![image](https://user-images.githubusercontent.com/730811/232511303-712ca68a-2c7d-41af-98d5-59c0e470ac66.png)

**Comment by WhyNotHugo** [comment]
Right, I _think_ a new config is needed (`padding`) which by default is equal to the corner radius (which would prevent changing how the default works).

**Comment by MaxVerevkin** [comment]
I added `padding` in 332e999

**Comment by WhyNotHugo** [comment]
The padding ends up being somewhat unequal.  I think it's because there's some extra padding on top, but not on the sides:

![image](https://user-images.githubusercontent.com/730811/232538634-ea6c8ee9-4fdc-49d6-879a-0e047061fb49.png)

It's still definitely an improvement.

**Comment by WhyNotHugo** [comment]
Yeah, with my fonts the red rectangles have a lot of padding on top, but none on the sides.

I suspect this is related to font metrics. The real issue is gone here, thanks!

**Comment by MaxVerevkin** [comment]
I fixed that option and it looks like this for me: 
![image](https://user-images.githubusercontent.com/34583604/232559476-c4f31da1-3f38-4f70-ae01-d240334318bf.png)

By the way, which font do you use?

**Comment by WhyNotHugo** [comment]
`monospace 10`, which I think falls back to `Noto Sans`.

**Comment by WhyNotHugo** [comment]
This was earlier today:

![image](https://user-images.githubusercontent.com/730811/232562839-f54ca449-0c88-4233-91e7-e4490cbddc68.png)

But I see the borders have changed now:

![image](https://user-images.githubusercontent.com/730811/232563004-a751de5f-4faa-4200-ae45-39013813a26e.png)

I think an issue here is that the arrows are too tall, so that leaves a lot of space on top and underneath the text which gives an impression of extra padding.

**Comment by MaxVerevkin** [comment]
I made the arrow configurable, so you can make it smaller with pango markup:

```yaml
separator: "<span size='small'> ➜ </span>"
````

**Comment by MaxVerevkin** [comment]
I also suppose padding can be more customizable, i.e. `padding_top`, `padding_right` and so on.
