### ISSUE TITLE
Make Ctrl+g and Ctrl+[ also close wlr-which-key menu

### ISSUE THREAD

**Issue by Seme4eg** [MaxVerevkin/wlr-which-key#6]
Those sequences are pretty common for many people that are using vim/emacs and other utilities that have those bindings as an escape sequence. Or at least add configuration option to add your own escape sequence bindings.

**Comment by Vaisakhkm2625** [comment]
how to bind anything with ctrl ?

**Comment by MaxVerevkin** [comment]
Modifiers are now supported (6d9e8aca9f175f6d402526d07ee2de7f2b233f30). Ctrl+[ and Ctrl+g now act like Esc when not defined explicitly (78952cb9c7825466e95c72ad33683a863059c7da).
